const mongoose = require('mongoose');
const Employee = require('./models/employee'); // Adjust path if needed

const employees = [{
    id: 1,
    naam: "Aarav Sharma",
    email: "employee1@example.com",
    password: "123",
    tasks: [
        {
            active: true,
            newTask: true,
            completed: false,
            failed: false,
            title: "Prepare Monthly Report",
            description: "Compile and submit the monthly sales report.",
            date: "2025-05-01",
            category: "Reporting",
            priority: "high",
        },
        {
            active: false,
            newTask: false,
            completed: true,
            failed: false,
            title: "Client Follow-up",
            description: "Email clients regarding project updates.",
            date: "2025-04-20",
            category: "Communication",
            priority: "medium",
        },
        {
            active: false,
            newTask: false,
            completed: false,
            failed: true,
            title: "Server Maintenance",
            description: "Scheduled maintenance missed deadline.",
            date: "2025-04-15",
            category: "IT Operations",
            priority: "low",
        },
    ],
},
{
    id: 2,
    naam: "Ishita Verma",
    email: "employee2@example.com",
    password: "123",
    tasks: [
        {
            active: true,
            newTask: true,
            completed: false,
            failed: false,
            title: "UI Redesign",
            description: "Redesign the dashboard interface.",
            date: "2025-05-03",
            category: "Design",
            priority: "high",
        },
        {
            active: false,
            newTask: false,
            completed: true,
            failed: false,
            title: "Team Meeting",
            description: "Conduct weekly scrum meeting.",
            date: "2025-04-30",
            category: "Management",
            priority: "medium",
        },
        {
            active: false,
            newTask: false,
            completed: true,
            failed: false,
            title: "Database Cleanup",
            description: "Remove outdated records.",
            date: "2025-04-28",
            category: "Database",
            priority: "low",
        },
        {
            active: false,
            newTask: false,
            completed: false,
            failed: true,
            title: "API Debugging",
            description: "Fix critical bug in payment API.",
            date: "2025-04-25",
            category: "Development",
            priority: "high",
        },
    ],
},
{
    id: 3,
    naam: "Rohan Gupta",
    email: "employee3@example.com",
    password: "123",
    tasks: [
        {
            active: true,
            newTask: true,
            completed: false,
            failed: false,
            title: "Inventory Audit",
            description: "Verify all stock items in warehouse.",
            date: "2025-05-04",
            category: "Logistics",
            priority: "medium",
        },
        {
            active: false,
            newTask: false,
            completed: true,
            failed: false,
            title: "Vendor Coordination",
            description: "Coordinate with vendors for deliveries.",
            date: "2025-04-22",
            category: "Supply Chain",
            priority: "low",
        },
    ],
},
{
    id: 4,
    naam: "Ananya Singh",
    email: "employee4@example.com",
    password: "123",
    tasks: [
        {
            active: true,
            newTask: true,
            completed: false,
            failed: false,
            title: "User Testing",
            description: "Conduct A/B tests on new features.",
            date: "2025-05-02",
            category: "QA",
            priority: "high",
        },
        {
            active: false,
            newTask: false,
            completed: false,
            failed: true,
            title: "Compliance Update",
            description: "Update system with latest compliance standards.",
            date: "2025-04-18",
            category: "Legal",
            priority: "medium",
        },
        {
            active: false,
            newTask: false,
            completed: true,
            failed: false,
            title: "System Backup",
            description: "Create a full backup of servers.",
            date: "2025-04-27",
            category: "IT Operations",
            priority: "low",
        },
    ],
},
{
    id: 5,
    naam: "Priya Nair",
    email: "employee5@example.com",
    password: "123",
    tasks: [
        {
            active: true,
            newTask: false,
            completed: false,
            failed: false,
            title: "Blog Post Writing",
            description: "Write blog post on new product feature.",
            date: "2025-05-03",
            category: "Marketing",
            priority: "medium",
        },
        {
            active: false,
            newTask: false,
            completed: true,
            failed: false,
            title: "Newsletter Design",
            description: "Design monthly email newsletter.",
            date: "2025-04-21",
            category: "Design",
            priority: "high",
        },
        {
            active: false,
            newTask: false,
            completed: false,
            failed: true,
            title: "Campaign Analytics",
            description: "Analyze performance of last campaign.",
            date: "2025-04-19",
            category: "Analytics",
            priority: "low",
        },
        {
            active: false,
            newTask: false,
            completed: true,
            failed: false,
            title: "Social Media Planning",
            description: "Plan content for upcoming week.",
            date: "2025-04-24",
            category: "Marketing",
            priority: "medium",
        },
    ],
},
{
    id: 6,
    naam: "Avi Jash",
    email: "avijash@gmail.com",
    password: "avichhavi",
    tasks: [
        {
            active: false,
            newTask: true,
            completed: false,
            failed: false,
            title: "Bring a rough register",
            description: "Tommorrow bring a rough register for notes and Assignment.",
            date: "2025-05-03",
            category: "College",
            priority: "high",
        },
        {
            active: false,
            newTask: true,
            completed: false,
            failed: false,
            title: "Bring Computer Networks Lab file printed",
            description: "Bring Computer Networks Lab file printed. It is very important.",
            date: "2025-04-21",
            category: "College",
            priority: "high",
        },
        {
            active: false,
            newTask: true,
            completed: false,
            failed: false,
            title: "Bring a pillow  for sleep",
            description: "To Maintain Sleep - Work cycle",
            date: "2025-04-19",
            category: "Sleep",
            priority: "low",
        },
        {
            active: true,
            newTask: true,
            completed: false,
            failed: false,
            title: "submit Proposal",
            description: "Major Project Proposal Submission",
            date: "2025-05-06",
            category: "Data Analysis",
            priority: "low",
        },
    ],
},
{
    id: 7,
    naam: "Ayush Srivastava",
    email: "exampleayush@gmail",
    password: "itsme115",
    tasks: [
        {
            active: false,
            newTask: true,
            completed: false,
            failed: false,
            title: "Bring a rough register",
            description: "Tommorrow bring a rough register for notes and Assignment.",
            date: "2025-05-03",
            category: "College",
            priority: "high",
        },
        {
            active: false,
            newTask: true,
            completed: false,
            failed: false,
            title: "Bring Computer Networks Lab file printed",
            description: "Bring Computer Networks Lab file printed. It is very important.",
            date: "2025-04-21",
            category: "College",
            priority: "high",
        },
        {
            active: false,
            newTask: true,
            completed: false,
            failed: false,
            title: "Bring a pillow  for sleep",
            description: "To Maintain Sleep - Work cycle",
            date: "2025-04-19",
            category: "Sleep",
            priority: "low",
        },
    ],
},

{
    id: 8,
    naam: "Aryan Katiyar",
    email: "aryankatiyar@gmail.com",
    password: "123456789",
    tasks: [
        {
            active: true,
            newTask: true,
            completed: false,
            failed: false,
            title: "Apply JSTMs, CNN, GAN on the dataset",
            description: "Implement JSTMs, CNN, and GAN models on the provided dataset for experimentation.",
            date: "2025-05-06",
            category: "Deep Learning",
            priority: "high",
        },
        {
            active: true,
            newTask: true,
            completed: false,
            failed: false,
            title: "Apply Linear Regressor",
            description: "Use linear regression on the dataset and evaluate performance metrics.",
            date: "2025-05-06",
            category: "Machine Learning",
            priority: "medium",
        },
        {
            active: true,
            newTask: true,
            completed: false,
            failed: false,
            title: "Draw All Pictorial Analysis of the Data",
            description: "Generate visualizations like histograms, scatter plots, and correlation matrices.",
            date: "2025-05-06",
            category: "Data Analysis",
            priority: "medium",
        },
        {
            active: true,
            newTask: true,
            completed: false,
            failed: false,
            title: "Submit Proposal",
            description: "Major Project Proposal Submission",
            date: "2025-05-06",
            category: "Data Analysis",
            priority: "low",
        },
    ],
}];

mongoose.connect('mongodb://localhost:27017/EMA', {
    useNewUrlParser: true,
    useUnifiedTopology: true,
})
    .then(async () => {
        console.log("MongoDB connected");

        try {
            await Employee.deleteMany(); // Optional: clears existing data
            await Employee.insertMany(employees);
            console.log("Employees seeded successfully!");
        } catch (err) {
            console.error("Error seeding employees:", err);
        } finally {
            mongoose.disconnect();
        }
    })
    .catch(err => console.error("MongoDB connection error:", err));
